Repository VerifyTests/Verify, pull requests merged in 2020-05, with the labels that each got.

#108 should scrub type when used as key
  docs/serializer-settings.md
  src/Verify.Tests/Serialization/SerializationTests.ShouldScrubDictionaryKey.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/CustomContractResolver.cs
Labels: Bug

#110 Simplify file nesting
  src/Verify/build/Verify.targets
Labels: Bug

#117 Add support for custom directory for verified files
  docs/build-server.md
  docs/mdsource/build-server.source.md
  docs/mdsource/doc-index.include.md
  docs/mdsource/received-ci.source.md
  docs/naming.md
  docs/readme.md
  docs/received-ci.md
  docs/serializer-settings.md
  readme.md
  src/DeterministicTests/DeterministicTests.csproj
  src/Directory.Build.props
  src/Verify.Tests/NamerTests.DeriveTestDirectory.verified.txt
  src/Verify.Tests/NamerTests.cs
  src/Verify.Tests/Snippets/Snippets.cs
  src/Verify/DeriveTestDirectory/DeriveTestDirectory.cs
  src/Verify/DeriveTestDirectory/SharedVerifySettings.cs
  src/Verify/Guard.cs
  src/Verify/Verifier/InnerVerifier.cs
  src/Verify/VerifySettings.cs
  src/Verify/build/Verify.targets
Labels: Feature

#118 Mark DeterministicSourcePaths as false for consuming projects
  src/Directory.Build.props
  src/Verify.Bunit/build.targets
  src/Verify.MSTest/build.targets
  src/Verify.NUnit/build.targets
Labels: Bug

#120 Move to StringBuilder for scrubbers
  src/Verify.Tests/ClipboardEnabledTests.cs
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify.Tests/Tests.Newlines.verified.txt
  src/Verify.Tests/Tests.cs
  src/Verify/Compare/CompareResult.cs
  src/Verify/Compare/Comparer.cs
  src/Verify/FileHelpers.cs
  src/Verify/FileHelpers_2.0.cs
  src/Verify/FileHelpers_2.1.cs
  src/Verify/Serialization/JsonFormatter.cs
  src/Verify/Serialization/Scrubbers/ApplyScrubbers.cs
  src/Verify/Serialization/Scrubbers/LinesScrubber.cs
  src/Verify/Serialization/Scrubbers/Scrubbers.cs
  src/Verify/Serialization/Scrubbers/SharedVerifySettings.cs
  src/Verify/Serialization/Scrubbers/VerifySettings.cs
  src/Verify/StringBuilderExtensions.cs
  src/Verify/Verifier/InnerVerifier_Stream.cs
  src/Verify/Verifier/InnerVerifier_Text.cs
  src/Verify/Verifier/StreamExtensions.cs
  src/Verify/VerifySettings.cs
Labels: Feature

#121 remove IgnoreTrailingWhitespace
  docs/serializer-settings.md
  src/Verify.Tests/Serialization/SerializationTests.NewLineNotEscapedInProperty.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.TrailingWhitespace.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Compare/Comparer.cs
  src/Verify/Serialization/JsonFormatter.cs
  src/Verify/Serialization/VerifySettings.cs
  src/Verify/Verifier/InnerVerifier_Json.cs
  src/Verify/Verifier/InnerVerifier_Text.cs
  src/Verify/VerifySettings.cs
Labels: Improvement

#122 dont trim trailing newline
  src/Directory.Build.props
  src/Verify.Bunit.Tests/VerifyObjectSamples.Anon.verified.txt
  src/Verify.Bunit.Tests/VerifyObjectSamples.ScopedSerializer.verified.txt
  src/Verify.MSTest.Tests/Snippets/ExtensionSample.AtMethod.verified.xml
  src/Verify.MSTest.Tests/VerifyObjectSamples.Anon.verified.txt
  src/Verify.MSTest.Tests/VerifyObjectSamples.ScopedSerializer.verified.txt
  src/Verify.NUnit.Tests/Snippets/ExtensionSample.AtMethod.verified.xml
  src/Verify.NUnit.Tests/VerifyObjectSamples.Anon.verified.txt
  src/Verify.NUnit.Tests/VerifyObjectSamples.ScopedSerializer.verified.txt
  src/Verify.Tests/Converters/TypeConverterTests.ConvertWithNewline.verified.txt
  src/Verify.Tests/LinesScrubberTests.DontScrubTrailingNewline.verified.txt
  src/Verify.Tests/LinesScrubberTests.FilterLines.verified.txt
  src/Verify.Tests/LinesScrubberTests.ScrubLinesContaining.verified.txt
  src/Verify.Tests/LinesScrubberTests.ScrubLinesContaining_case_sensitive.verified.txt
  src/Verify.Tests/LinesScrubberTests.cs
  src/Verify.Tests/Serialization/SerializationTests.NewLineNotEscapedInProperty.verified.txt
  src/Verify.Tests/Tests.Newlines.verified.txt
  src/Verify.Tests/Tests.NewlinesText.verified.txt
  src/Verify.Tests/Tests.cs
  src/Verify.Xunit.Tests/Snippets/ExtensionSample.AtMethod.verified.xml
  src/Verify.Xunit.Tests/Snippets/SampleTest.Simple.verified.txt
  src/Verify.Xunit.Tests/VerifyObjectSamples.Anon.verified.txt
  src/Verify.Xunit.Tests/VerifyObjectSamples.ScopedSerializer.verified.txt
  src/Verify/Serialization/Scrubbers/LinesScrubber.cs
  src/Verify/StringBuilderExtensions.cs
  src/Verify/Verifier/InnerVerifier_Text.cs
  src/Verify/Verifier/StreamExtensions.cs
Labels: Bug

#124 fix escaping in json
  docs/serializer-settings.md
  src/Directory.Build.props
  src/Verify.Tests/Serialization/SerializationTests.NewLineEscapedInProperty.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.NewLineNotEscapedInProperty.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify.Tests/Tests.cs
  src/Verify/Serialization/JsonFormatter.cs
  src/Verify/Serialization/Scrubbers/StringConverter.cs
  src/Verify/Serialization/Scrubbers/VerifySettings.cs
  src/Verify/Serialization/StringWriterEx.cs
  src/Verify/Verifier/InnerVerifier_Json.cs
  src/Verify/Verifier/InnerVerifier_Stream.cs
Labels: Bug

#125 fix bad new lines in scrubber
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  src/Directory.Build.props
  src/Verify.Tests/Serialization/SerializationTests.ScrubberWithBadNewLine.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/Scrubbers/ApplyScrubbers.cs
  src/Verify/Verifier/InnerVerifier_Json.cs
  src/Verify/Verifier/InnerVerifier_Text.cs
Labels: Bug

#129 update to bunit 1.0.0-beta-7
  src/Directory.Build.props
  src/Verify.Bunit/ComponentReader.cs
  src/Verify.Bunit/VerifyBase.cs
  src/Verify.Bunit/VerifyBase_File.cs
  src/Verify.Bunit/VerifyBase_Json.cs
  src/Verify.Bunit/VerifyBase_Text.cs
  src/Verify.Bunit/VerifyBase_Tuple.cs
  src/Verify.Xunit/VerifyBase_File.cs
  src/Verify.Xunit/VerifyBase_Text.cs
Labels: Feature

#130 Pass instance to converter
  src/Verify.Tests/Converters/TypeConverterTests.ConvertWithCanConvert_Invalid.verified.txt
  src/Verify.Tests/Converters/TypeConverterTests.ConvertWithCanConvert_Valid.verified.txt
  src/Verify.Tests/Converters/TypeConverterTests.cs
  src/Verify/Splitters/Delegates/AsyncConversion.cs
  src/Verify/Splitters/Delegates/CanConvert.cs
  src/Verify/Splitters/Delegates/Conversion.cs
  src/Verify/Splitters/Settings_Extension.cs
  src/Verify/Splitters/Settings_Typed.cs
  src/Verify/Splitters/StreamConverter.cs
  src/Verify/Splitters/TypeConverter.cs
  src/Verify/Verifier/InnerVerifier_Json.cs
Labels: Feature

#137 add inline guid processing
  docs/mdsource/serializer-settings.source.md
  docs/named-tuples.md
  docs/naming.md
  docs/scrubbers.md
  docs/serializer-settings.md
  src/Verify.Tests/Serialization/SerializationTests.ShouldBeAbleToExcludeInlineGuids.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldScrubInlineGuidsByDefault.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/JsonFormatter.cs
  src/Verify/Serialization/Scrubbers/SharedScrubber.cs
  src/Verify/Serialization/SerializationSettings.cs
Labels: Feature
