Repository VerifyTests/Verify, pull requests merged in 2021-09, with the labels that each got.

#399 Using JToken.Parse instead of JObject.Parse in VerifyJson
  docs/serializer-settings.md
  src/StrictJsonTests/Tests.VerifyJsonArrayString.verified.json
  src/StrictJsonTests/Tests.cs
  src/Verify/Verifier/InnerVerifier_Json.cs
Labels: Feature

#398 Allow user to sort serialized properties alphabetically
  src/Verify.Tests/Serialization/SerializationTests.SortingPropertiesAlphabeticallyDoesNotAffectTypeName.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.SortsPropertiesAlphabetically.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/CustomContractResolver.cs
  src/Verify/Serialization/VerifierSettings.cs
Labels: Feature

#400 Add verify tuple
  docs/named-tuples.md
  src/Directory.Build.props
  src/Verify.MSTest/VerifyBase_Tuple.cs
  src/Verify.NUnit/Verifier_Tuple.cs
  src/Verify.NUnit/VerifyBase_Tuple.cs
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify.Xunit/Verifier_Tuple.cs
  src/Verify.Xunit/VerifyBase_Tuple.cs
  src/Verify/Verifier/InnerVerifier_Tuple.cs
Labels: Improvement

#407 Regex guid fix
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Directory.Build.props
  src/Verify.Tests/Serialization/SerializationTests.ShouldBeAbleToExcludeInlineGuidsWrappedInSymbols.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldNotExcludeInlineGuidsWrappedInDash.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldNotExcludeInlineGuidsWrappedInLetters.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldNotExcludeInlineGuidsWrappedInNumber.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/Scrubbers/GuidScrubber.cs
Labels: Bug

#409 respect empty guild in Scrubbing
  docs/serializer-settings.md
  readme.md
  src/Directory.Build.props
  src/Verify.Tests/Serialization/SerializationTests.ShouldRespectEmptyGuid.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/Scrubbers/GuidScrubber.cs
  src/Verify/Serialization/Scrubbers/SharedScrubber.cs
  src/Verify/Serialization/Scrubbers/SharedScrubber_Dates.cs
  src/Verify/Serialization/Scrubbers/SharedScrubber_Guids.cs
Labels: Improvement

#410 Respect Min and Max dates in scrubbing
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Verify.Tests/Serialization/SerializationTests.DatetimeMax.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.DatetimeMin.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/Scrubbers/SharedScrubber.cs
  src/Verify/Serialization/Scrubbers/SharedScrubber_Dates.cs
Labels: Feature
