Repository VerifyTests/Verify, pull requests merged in 2021-11, with the labels that each got.

#433 Add id convention
  docs/mdsource/serializer-settings.source.md
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Verify.Tests/Serialization/SerializationTests.TreatAsNumericId.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.TreatAsNumericIdGlobal.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/CustomContractResolver.cs
  src/Verify/Serialization/IsNumericId.cs
  src/Verify/Serialization/SerializationSettings.cs
Labels: Feature

#436 trim trailing end from exception message on diff
  src/Verify/Verifier/VerifyEngine.cs
Labels: Improvement

#437 throw for custom DateFormatHandling
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Directory.Build.props
  src/Verify.NUnit.Tests/VerifyObjectSamples.ScopedSerializer.verified.txt
  src/Verify.NUnit.Tests/VerifyObjectSamples.ScopedSerializerFluent.verified.txt
  src/Verify.NUnit.Tests/VerifyObjectSamples.cs
  src/Verify.Tests/Serialization/SerializationTests.ThrowForDateFormatHandling.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ThrowForDateFormatString.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ThrowForDateTimeZoneHandling.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/SerializationSettings.cs
Labels: Improvement

#438 add explicit IgnoreStackTrack
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Directory.Build.props
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify.Tests/Tests.cs
  src/Verify/Serialization/VerifierSettings.cs
  src/Verify/Serialization/VerifySettings.cs
  src/Verify/SettingsTask.cs
Labels: Feature

#439 add instance level appenders
  docs/serializer-settings.md
  src/Directory.Build.props
  src/Verify.Tests/Converters/JsonAppenderTests.WithLocalJsonAppender.verified.txt
  src/Verify.Tests/Converters/JsonAppenderTests.cs
  src/Verify.Tests/Tests.VerifyFileWithAppend.00.verified.txt
  src/Verify.Tests/Tests.VerifyFileWithAppend.01.verified.txt
  src/Verify.Tests/Tests.cs
  src/Verify/Serialization/VerifySettings.cs
  src/Verify/SettingsTask.cs
  src/Verify/Splitters/Settings_JsonAppender.cs
  src/Verify/Verifier/InnerVerifier_Inner.cs
  src/Verify/VerifySettings.cs
Labels: Improvement

#440 fix netcore naming
  src/Verify.Tests/Naming/CustomFileName.Core.verified.txt
  src/Verify.Tests/Naming/NamerTests.Runtime.Core.verified.txt
  src/Verify.Tests/Naming/NamerTests.RuntimeAndVersion.Core3_1.verified.txt
  src/Verify.Tests/Naming/NamerTests.RuntimeAndVersionFluent.Core3_1.verified.txt
  src/Verify.Tests/Naming/NamerTests.RuntimeFluent.Core.verified.txt
  src/Verify.Tests/Naming/NamerTests.TargetFramework.Core.verified.txt
  src/Verify.Tests/Naming/NamerTests.TargetFrameworkAndVersion.Core3_1.verified.txt
  src/Verify.Tests/Naming/NamerTests.TargetFrameworkAndVersionFluent.Core3_1.verified.txt
  src/Verify.Tests/Naming/NamerTests.TargetFrameworkFluent.Core.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify.Tests/Tests.ThrowsAggregate.Core.verified.txt
  src/Verify.Tests/Tests.ThrowsTask.Core.verified.txt
  src/Verify.Tests/Tests.ThrowsTaskGeneric.Core.verified.txt
  src/Verify.Tests/Tests.ThrowsValueTask.Core.verified.txt
  src/Verify.Tests/Tests.ThrowsValueTaskGeneric.Core.verified.txt
  src/Verify.Tests/Verify.Tests.csproj
  src/Verify/Naming/Namer.cs
Labels: Bug

#442 Create settings based on other settings with correct Append value
  src/Verify/VerifySettings.cs
Labels: Bug
