Repository VerifyTests/Verify, pull requests merged in 2021-05, with the labels that each got.

#345 add nullable support to WriteOnlyJsonConverter<T>
  src/Directory.Build.props
  src/Verify/Serialization/Converters/DateTimeConverter.cs
  src/Verify/Serialization/Converters/DateTimeOffsetConverter.cs
  src/Verify/Serialization/Converters/GuidConverter.cs
  src/Verify/Serialization/WriteOnlyJsonConverterT.cs
Labels: Improvement

#348 Verifier before after callbacks
  docs/build-server.md
  docs/clipboard.md
  docs/mdsource/verify-options.source.md
  docs/naming.md
  docs/serializer-settings.md
  docs/verify-options.md
  src/Directory.Build.props
  src/Verify.Tests/Snippets/Snippets.cs
  src/Verify/Callbacks/VerifySettings.cs
  src/Verify/Counters/CounterContext.cs
  src/Verify/Verifier/InnerVerifier.cs
  src/Verify/Verifier/VerifyEngine.cs
Labels: Feature

#351 Scrub numeric ids
  docs/mdsource/serializer-settings.source.md
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Directory.Build.props
  src/Verify.Tests/Serialization/SerializationTests.NumericIdScrubbing.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.NumericIdScrubbingDisabled.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.NumericIdScrubbingDisabledGlobal.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Counters/CounterContext.cs
  src/Verify/Serialization/Converters/IdConverter.cs
  src/Verify/Serialization/CustomContractResolver.cs
  src/Verify/Serialization/SerializationSettings.cs
Labels: Feature

#352 Add support for scrubbing nullable numeric IDs
  docs/mdsource/serializer-settings.source.md
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Verify.Tests/Serialization/SerializationTests.NumericIdScrubbing.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.NumericIdScrubbingDisabled.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.NumericIdScrubbingDisabledGlobal.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/CustomContractResolver.cs
Labels: Bug

#354 update DiffEngine to 6.8.0
  src/DeterministicTests/DeterministicTests.csproj
  src/Directory.Build.props
  src/DisableClipboard/DisableClipboard.csproj
  src/DisableDirScrubbing/DisableDirScrubbing.csproj
  src/Naming/NamingTests.csproj
  src/StrictJsonTests/StrictJsonTests.csproj
  src/Verify.DerivePaths.Tests/Verify.DerivePaths.Tests.csproj
  src/Verify.Integration.Tests/Verify.Integration.Tests.csproj
  src/Verify.Tests/Verify.Tests.csproj
  src/Verify/Verify.csproj
Labels: Feature

#355 Add UseTextForParameters
  docs/mdsource/naming.source.md
  docs/mdsource/parameterised.source.md
  docs/naming.md
  docs/parameterised.md
  src/Naming/Tests.cs
  src/Verify.DerivePaths.Tests/CustomDir/CustomTypeName.ThrowOnConflict.verified.txt
  src/Verify.Tests/Naming/NamerTests.UseTextForParametersFluent_Value1.verified.txt
  src/Verify.Tests/Naming/NamerTests.UseTextForParametersFluent_Value2.verified.txt
  src/Verify.Tests/Naming/NamerTests.UseTextForParameters_Value1.verified.txt
  src/Verify.Tests/Naming/NamerTests.UseTextForParameters_Value2.verified.txt
  src/Verify.Tests/Naming/NamerTests.cs
  src/Verify.Tests/SimpleTypeTests.cs
  src/Verify.Xunit/Verifier.cs
  src/Verify/Naming/FileNameBuilder.cs
  src/Verify/Naming/ParameterSettings.cs
  src/Verify/SettingsTask.cs
  src/Verify/Verifier/InnerVerifier.cs
  src/Verify/VerifySettings.cs
Labels: Feature

#363 In json dont write space after colon when newline detected in value
  docs/http-recording.md
  src/Verify.DerivePaths.Tests/CustomDir/CustomTypeName.ThrowOnConflict.verified.txt
  src/Verify.Tests/ClipboardEnabledTests.ParseEnvironmentVariable_failure.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.NewLineNotEscapedInProperty.verified.txt
  src/Verify.Tests/Tests.JsonGet.verified.txt
  src/Verify.Tests/Tests.ShouldThrowForExtensionOnSerialization.verified.txt
  src/Verify.Tests/Tests.TestHttpRecording.verified.txt
  src/Verify.Tests/Tests.TestHttpRecordingWithResponse.verified.txt
  src/Verify.Tests/Tests.Throws.verified.txt
  src/Verify.Tests/Tests.ThrowsAggregate.DotNet.verified.txt
  src/Verify.Tests/Tests.ThrowsAggregate.Net.verified.txt
  src/Verify.Tests/Tests.ThrowsArgumentException.verified.txt
  src/Verify.Tests/Tests.ThrowsInheritedArgumentException.verified.txt
  src/Verify.Tests/Tests.ThrowsNested.verified.txt
  src/Verify.Tests/Tests.ThrowsTask.DotNet.verified.txt
  src/Verify.Tests/Tests.ThrowsTask.Net.verified.txt
  src/Verify.Tests/Tests.ThrowsTaskGeneric.DotNet.verified.txt
  src/Verify.Tests/Tests.ThrowsTaskGeneric.Net.verified.txt
  src/Verify.Tests/Tests.ThrowsValueTask.DotNet.verified.txt
  src/Verify.Tests/Tests.ThrowsValueTask.Net.verified.txt
  src/Verify.Tests/Tests.ThrowsValueTaskGeneric.DotNet.verified.txt
  src/Verify.Tests/Tests.ThrowsValueTaskGeneric.Net.verified.txt
  src/Verify.Tests/Tests.WithNewline.verified.txt
  src/Verify/Serialization/JsonFormatter.cs
  src/Verify/Serialization/JsonTextWriterEx.cs
Labels: Feature

#368 Replace invalid param chars
  docs/http-recording.md
  docs/logging-recording.md
  docs/mdsource/parameterised.source.md
  docs/parameterised.md
  src/Directory.Build.props
  src/Verify.Tests/Tests.ReplaceInvalidParamChar_value=-.verified.txt
  src/Verify.Tests/Tests.cs
  src/Verify/Guard.cs
  src/Verify/Naming/FileNameBuilder.cs
  src/Verify/Naming/VerifierSettings.cs
Labels: Improvement

#370 net 6 support including DateOnly and TimeOnly
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Verify.Tests/Serialization/SerializationTests.ShouldReUseDatetime.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldScrubDatetime.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.TimeOnlyNested.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify.Tests/SimpleTypeTests.Half.verified.txt
  src/Verify.Tests/SimpleTypeTests.Run_arg=System.DateOnly.verified.txt
  src/Verify.Tests/SimpleTypeTests.Run_arg=System.Half.verified.txt
  src/Verify.Tests/SimpleTypeTests.Run_arg=System.TimeOnly.verified.txt
  src/Verify.Tests/SimpleTypeTests.cs
  src/Verify/Counters/CounterContext.cs
  src/Verify/Serialization/Converters/DateConverter.cs
  src/Verify/Serialization/Converters/TimeConverter.cs
  src/Verify/Serialization/Scrubbers/SharedScrubber.cs
  src/Verify/Serialization/SerializationSettings.cs
  src/Verify/Serialization/VerifierSettings.cs
  src/global.json
Labels: Feature
