Repository VerifyTests/Verify, pull requests merged in 2022-02, with the labels that each got.

#469 Split out clipboard to a different nuget
  docs/build-server.md
  docs/clipboard.md
  docs/mdsource/clipboard.source.md
  docs/naming.md
  docs/serializer-settings.md
  docs/verify-options.md
  readme.md
  readme.source.md
  src/Directory.Build.props
  src/DisableClipboard/DisableClipboardTests.cs
  src/Verify.ClipboardAccept.Tests/ClipboardEnabledTests.ParseEnvironmentVariable_failure.verified.txt
  src/Verify.ClipboardAccept.Tests/ClipboardEnabledTests.cs
  src/Verify.ClipboardAccept.Tests/Verify.ClipboardAccept.Tests.csproj
  src/Verify.ClipboardAccept/ClipboardAccept.cs
  src/Verify.ClipboardAccept/ClipboardEnabled.cs
  src/Verify.ClipboardAccept/InternalsVisibleTo.cs
  src/Verify.ClipboardAccept/Verify.ClipboardAccept.csproj
  src/Verify.Integration.Tests/Tests.cs
  src/Verify.Integration.Tests/Verify.Integration.Tests.csproj
  src/Verify.Tests/Snippets/Snippets.cs
  src/Verify.sln
  src/Verify/Callbacks/VerifyDelete.cs
  src/Verify/Callbacks/VerifySettings.cs
  src/Verify/Clipboard/VerifierSettings.cs
  src/Verify/Verifier/VerifyEngine.cs
  src/Verify/Verify.csproj
Labels: Improvement, Breaking change

#472 Run less specific scrubbers last
  docs/named-tuples.md
  docs/serializer-settings.md
  readme.md
  src/Directory.Build.props
  src/Verify.Tests/Serialization/SerializationTests.MoreSpecificScrubberShouldOverride.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/DerivePaths/VerifierSettings.cs
  src/Verify/Serialization/Scrubbers/ApplyScrubbers.cs
  src/Verify/Serialization/Scrubbers/VerifierSettings.cs
  src/Verify/Serialization/VerifierSettings.cs
  src/Verify/TargetAssembly.cs
Labels: Improvement

#480 add tostring support for xmldocument
  docs/serializer-settings.md
  src/Directory.Build.props
  src/Verify.Tests/SimpleTypeTests.Run_arg=System.Xml.XmlDocument.verified.txt
  src/Verify.Tests/SimpleTypeTests.Run_arg=System.Xml.XmlDocument.verified.xml
  src/Verify/Serialization/VerifierSettings.cs
Labels: Improvement

#485 Fixing failure when .sln is located in root directory
  src/ApplyScrubbersTests/ApplyScrubbersTests.csproj
  src/ApplyScrubbersTests/DisableDirScrubbingTests.ProjectDirectory.verified.txt
  src/ApplyScrubbersTests/DisableDirScrubbingTests.SolutionDirectory.verified.txt
  src/ApplyScrubbersTests/DisableDirScrubbingTests.cs
  src/Verify.sln
  src/Verify/InternalsVisibleTo.cs
  src/Verify/Serialization/Scrubbers/ApplyScrubbers.cs
Labels: Bug

#481 Feature/ignore parameters for verified
  docs/mdsource/parameterised.source.md
  docs/parameterised.md
  src/Verify.Expecto/Verifier.cs
  src/Verify.Tests/Naming/NamerTests.IgnoreParametersForVerified.verified.txt
  src/Verify.Tests/Naming/NamerTests.IgnoreParametersForVerifiedFluent.verified.txt
  src/Verify.Tests/Naming/NamerTests.cs
  src/Verify/FilePair.cs
  src/Verify/Naming/ParameterSettings.cs
  src/Verify/Naming/ReflectionFileNameBuilder.cs
  src/Verify/SettingsTask.cs
  src/Verify/Verifier/GetFileConvention.cs
  src/Verify/Verifier/InnerVerifier.cs
  src/Verify/VerifySettings.cs
Labels: Feature

#486 DiffEngine 9.0.4
  src/Directory.Build.props
  src/Verify.ClipboardAccept/Verify.ClipboardAccept.csproj
  src/Verify/Verify.csproj
Labels: Improvement
