Repository VerifyTests/Verify, pull requests merged in 2022-08, with the labels that each got.

#562 remove duplicate scrubbing
  src/Verify/Serialization/Scrubbers/ApplyScrubbers.cs
Labels: Bug

#563 Always use RuntimeAndVersion on received
  readme.md
  src/OmitContentFromException/OmitContentFromExceptionTests.String.verified.txt
  src/Verify.ExceptionParsing.Tests/ExceptionParsingTests.cs
  src/Verify.Expecto/Verifier.cs
  src/Verify.MSTest/VerifyBase.cs
  src/Verify.NUnit/Verifier.cs
  src/Verify.Tests/Converters/ExtensionConverterTests.cs
  src/Verify.Tests/Naming/CustomFileNameWithUnique.Core.verified.txt
  src/Verify.Tests/Naming/CustomFileNameWithUnique.DotNet.verified.txt
  src/Verify.Tests/Naming/CustomFileNameWithUnique.Net.verified.txt
  src/Verify.Tests/Naming/NamerTests.cs
  src/Verify.Tests/Tests.DanglingFiles.Core2_1.verified.txt
  src/Verify.Tests/Tests.DanglingFiles.Core3_0.verified.txt
  src/Verify.Tests/Tests.DanglingFiles.Core3_1.verified.txt
  src/Verify.Tests/Tests.DanglingFiles.DotNet6_0.verified.txt
  src/Verify.Tests/Tests.DanglingFiles.Net4_6.verified.txt
  src/Verify.Tests/Tests.DanglingFiles.Net4_8.verified.txt
  src/Verify.Tests/Tests.DanglingFilesIgnoreParametersForVerified.Core2_1.verified.txt
  src/Verify.Tests/Tests.DanglingFilesIgnoreParametersForVerified.Core3_0.verified.txt
  src/Verify.Tests/Tests.DanglingFilesIgnoreParametersForVerified.Core3_1.verified.txt
  src/Verify.Tests/Tests.DanglingFilesIgnoreParametersForVerified.DotNet6_0.verified.txt
  src/Verify.Tests/Tests.DanglingFilesIgnoreParametersForVerified.Net4_6.verified.txt
  src/Verify.Tests/Tests.DanglingFilesIgnoreParametersForVerified.Net4_8.verified.txt
  src/Verify.Tests/Tests.cs
  src/Verify.Xunit/Verifier.cs
  src/Verify/FilePair.cs
  src/Verify/Naming/PrefixUnique.cs
  src/Verify/Naming/ReflectionFileNameBuilder.cs
  src/Verify/Verifier/GetFileConvention.cs
  src/Verify/Verifier/InnerVerifier.cs
Labels: Improvement

#566 Scrub only string members
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/ApplyScrubbersTests/DisableDirScrubbingTests.cs
  src/Verify.Tests/Serialization/SerializationTests.OnlyScrubInlineProperties.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubInlineGuids.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubberWithBadNewLine.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldNotExcludeInlineGuidsWrappedInNumber.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldNotScrubInlineGuidsEndingLetters.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldNotScrubInlineGuidsStartingInLetters.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldNotScrubInlineGuidsWrappedInDash.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldNotScrubInlineGuidsWrappedInLetters.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldNotScrubInlineGuidsWrappedInNumber.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldReUseDatetime2.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldScrubInlineGuidsEndingInNewline1.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldScrubInlineGuidsEndingInNewline2.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldScrubInlineGuidsStartingInNewline1.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldScrubInlineGuidsStartingInNewline2.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldScrubInlineGuidsWrappedInSymbols.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ShouldScrublineGuidsInString.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Extensions.cs
  src/Verify/Serialization/ArrayConverter.cs
  src/Verify/Serialization/Converters/DateConverter.cs
  src/Verify/Serialization/Converters/DictionaryConverter.cs
  src/Verify/Serialization/JsonFormatter.cs
  src/Verify/Serialization/Scrubbers/ApplyScrubbers.cs
  src/Verify/Serialization/Scrubbers/GuidScrubber.cs
  src/Verify/Serialization/VerifyJsonWriter.cs
  src/Verify/Verifier/InnerVerifier_Inner.cs
  src/Verify/Verifier/VerifyEngine.cs
Labels: Bug, Improvement

#565 Fix #564 - Handle empty user profile
  src/Verify/Serialization/Scrubbers/ApplyScrubbers.cs
Labels: Bug

#567 fix DateOnly with no scrubbing
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Verify.Tests/Serialization/SerializationTests.DateOnlyWithNoScrubbing.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/Converters/DateConverter.cs
Labels: Bug

#568 WriteRawValue where no escaping is known
  src/Verify/Serialization/Converters/ConstructorInfoConverter.cs
  src/Verify/Serialization/Converters/DateConverter.cs
  src/Verify/Serialization/Converters/DirectoryInfoConverter.cs
  src/Verify/Serialization/Converters/EncodingConverter.cs
  src/Verify/Serialization/Converters/ExpressionConverter.cs
  src/Verify/Serialization/Converters/FieldInfoConverter.cs
  src/Verify/Serialization/Converters/FileInfoConverter.cs
  src/Verify/Serialization/Converters/MethodInfoConverter.cs
  src/Verify/Serialization/Converters/ParameterInfoConverter.cs
  src/Verify/Serialization/Converters/PropertyInfoConverter.cs
  src/Verify/Serialization/Converters/TimeConverter.cs
  src/Verify/Serialization/Converters/TypeJsonConverter.cs
  src/Verify/Serialization/Converters/VersionConverter.cs
  src/Verify/Serialization/VerifyJsonWriter.cs
Labels: Improvement

#569 make machine name and user name scrubbing less greedy
  docs/named-tuples.md
  docs/serializer-settings.md
  readme.md
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubMachineName.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubMachineNameInValidAfter.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubMachineNameInValidBefore.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubMachineNameInValidWrapped.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubMachineNameValidAfter.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubMachineNameValidBefore.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubMachineNameValidWrapped.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubUserName.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubUserNameInValidAfter.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubUserNameInValidBefore.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubUserNameInValidWrapped.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubUserNameValidAfter.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubUserNameValidBefore.verified.txt
  src/ApplyScrubbersTests/ApplyScrubbersTests.ScrubUserNameValidWrapped.verified.txt
  src/ApplyScrubbersTests/DisableDirScrubbingTests.cs
  src/Verify.Tests/Serialization/SerializationTests.ScrubUserName.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/Scrubbers/Scrubbers.cs
Labels: Improvement

#571 better newline scrubbing
  docs/serializer-settings.md
  readme.md
  src/Directory.Build.props
  src/Verify.Tests/Serialization/SerializationTests.NotScrubNonStringDictionaryValues.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubBeforeNewline.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubDictionaryValue_BeforeValue.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubDictionaryValue_BeforeValueAfter.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubDictionaryValue_BeforeValueAfterNewLine.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubDictionaryValue_BeforeValueWithNewLine.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubDictionaryValue_NoMatch.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubDictionaryValue_Value.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubDictionaryValue_ValueAfter.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubDictionaryValue_ValueAfterWithNewLine.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubEmptyLineEnd.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubEmptyLinesEndProperty.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubEmptyLinesMiddle.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubEmptyLinesMiddleProperty.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubEmptyLinesStart.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubEmptyLinesStartAndEnd.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubEmptyLinesStartAndEndAndWhiteSpace.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubEmptyLinesStartAndEndAndWhiteSpaceProperty.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubEmptyLinesStartAndEndProperty.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubEmptyLinesStartProperty.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubPropertyBeforeNewline.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Extensions.cs
  src/Verify/Serialization/Scrubbers/VerifySettings.cs
  src/Verify/Serialization/VerifyJsonWriter.cs
Labels: Bug

#572 add WriteRawValueWithScrubbers
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Directory.Build.props
  src/StrictJsonTests/Tests.WriteRawInConverterTest.verified.json
  src/StrictJsonTests/Tests.cs
  src/Verify.Tests/Serialization/SerializationTests.WriteRawInConverterTest.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/VerifyJsonWriter.cs
Labels: Feature

#574 Ensure result has files for autoverify
  readme.md
  src/Verify.ExceptionParsing.Tests/ExceptionParsingTests.cs
  src/Verify.Tests/Tests.ResultAutoVerify.verified.txt
  src/Verify.Tests/Tests.cs
  src/Verify/Verifier/InnerVerifier_Inner.cs
  src/Verify/Verifier/VerifyEngine.cs
  src/Verify/Verifier/VerifyExceptionMessageBuilder.cs
Labels: Bug

#573 Missing UTF8 bom preamble on some runtimes
  readme.md
  src/Verify.Tests/Tests.EnsureUtf8BomPreamble.Core2_1.verified.txt
  src/Verify.Tests/Tests.EnsureUtf8BomPreamble.Core3_0.verified.txt
  src/Verify.Tests/Tests.EnsureUtf8BomPreamble.Core3_1.verified.txt
  src/Verify.Tests/Tests.EnsureUtf8BomPreamble.DotNet6_0.verified.txt
  src/Verify.Tests/Tests.EnsureUtf8BomPreamble.Net4_6.verified.txt
  src/Verify.Tests/Tests.EnsureUtf8BomPreamble.Net4_8.verified.txt
  src/Verify.Tests/Tests.cs
  src/Verify.Tests/Verify.Tests.csproj
  src/Verify/IoHelpers.cs
Labels: Bug

#579 Fix newline handling for xml document
  docs/serializer-settings.md
  src/Verify/Serialization/VerifierSettings.cs
Labels: Bug

#580 Handle bad newlines written by converter
  docs/serializer-settings.md
  readme.md
  src/Verify.Tests/Serialization/SerializationTests.TestConverterWithBadNewline.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Extensions.cs
  src/Verify/Serialization/JsonFormatter.cs
  src/Verify/Serialization/VerifyJsonWriter.cs
Labels: Bug

#581 Add StringBuilder.AppendLineN extension method
  src/Directory.Build.props
  src/Verify/Serialization/Scrubbers/LinesScrubber.cs
  src/Verify/Serialization/Scrubbers/Scrubbers.cs
  src/Verify/StringBuilderExtensions.cs
Labels: Feature

#582 Add AppendLineN for no string
  src/Directory.Build.props
  src/Verify/StringBuilderExtensions.cs
  src/Verify/Verifier/VerifyExceptionMessageBuilder.cs
Labels: Feature

#586 Add support for specifying Scrubber order
  docs/mdsource/scrubbers.source.md
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Verify.Tests/Serialization/SerializationTests.ScrubberInvertOrder.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify.Tests/Tests.cs
  src/Verify/Extensions.cs
  src/Verify/Serialization/Scrubbers/ScrubberLocation.cs
  src/Verify/Serialization/Scrubbers/VerifierSettings.cs
  src/Verify/Serialization/Scrubbers/VerifySettings.cs
  src/Verify/SettingsTask.cs
  src/Verify/SettingsTask_Scrubbing.cs
Labels: Feature

#588 DiffEngine Version 10.0.0
  src/Verify.ClipboardAccept/Verify.ClipboardAccept.csproj
  src/Verify/Verify.csproj
Labels: Feature

#594 fix TypeNameHandling for array items
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Verify.Tests/Serialization/SerializationTests.TypeNameHandlingInArray_typeHandling=All.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.TypeNameHandlingInArray_typeHandling=Arrays.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.TypeNameHandlingInArray_typeHandling=Auto.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.TypeNameHandlingInArray_typeHandling=None.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.TypeNameHandlingInArray_typeHandling=Objects.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/ArrayConverter.cs
  src/Verify/Serialization/CustomContractResolver.cs
Labels: Bug

#599 Fix broken IgnoreMember on inherited member
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Directory.Build.props
  src/Verify.Tests/Serialization/SerializationTests.IgnoreOnInterfaceChildTyped.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.IgnoreOnInterfaceNamed.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.IgnoreOnInterfaceTyped.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/SerializationSettings_IgnoreForMemberOfType.cs
Labels: Bug

#600 better guid scrubbing
  src/Verify.Tests/GuidScrubberTests.Run_bslash.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_curly.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_dash.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_end-bslash.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_end-curly.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_end-dash.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_end-fslash.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_end-letters.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_end-numbers.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_end-square.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_fslash.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_letters.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_numbers.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_simple.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_square.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_start-bslash.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_start-curly.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_start-dash.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_start-fslash.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_start-letters.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_start-numbers.verified.txt
  src/Verify.Tests/GuidScrubberTests.Run_start-square.verified.txt
  src/Verify.Tests/GuidScrubberTests.cs
  src/Verify/Serialization/Scrubbers/GuidScrubber.cs
Labels: Bug

#608 Add ScrubMember(s)
  docs/mdsource/serializer-settings.source.md
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Verify.Tests/Serialization/SerializationTests.AddScrubInstance.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.AddScrubInstanceFluent.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.JTokenScrub.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubDictionaryKeyByName.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubJTokenByName.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubMemberByExpression.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubMemberByExpressionFluent.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubMemberByName.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubMemberByNameFluent.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubMembersNullable.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubMembersNullableNested.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubType.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.ScrubTypeFluent.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Extensions.cs
  src/Verify/Serialization/ArrayConverter.cs
  src/Verify/Serialization/Converters/DictionaryConverter.cs
  src/Verify/Serialization/CustomContractResolver.cs
  src/Verify/Serialization/CustomValueProvider.cs
  src/Verify/Serialization/ScrubOrIgnore.cs
  src/Verify/Serialization/ScrubbedProvider.cs
  src/Verify/Serialization/Scrubbers/DictionaryWrappers/OrderedStringDictionaryWrapper.cs
  src/Verify/Serialization/Scrubbers/DictionaryWrappers/StringDictionaryWrapper.cs
  src/Verify/Serialization/SerializationSettings_IgnoreByName.cs
  src/Verify/Serialization/SerializationSettings_IgnoreForMemberOfType.cs
  src/Verify/Serialization/SerializationSettings_IgnoreInstance.cs
  src/Verify/Serialization/SerializationSettings_IgnoreType.cs
  src/Verify/Serialization/SerializationSettings_ShouldIgnore.cs
  src/Verify/Serialization/ShouldScrub.cs
  src/Verify/Serialization/VerifierSettings_SerializationMaps.cs
  src/Verify/Serialization/VerifyJsonWriter.cs
  src/Verify/Serialization/VerifySettings_SerializationMaps.cs
  src/Verify/SettingsTask_SerializationMaps.cs
Labels: Feature

#609 Add received text to OnFirstVerify
  docs/verify-options.md
  src/Verify.ClipboardAccept/ClipboardAccept.cs
  src/Verify.Tests/Snippets/Snippets.cs
  src/Verify.Tests/Tests.cs
  src/Verify/Callbacks/FirstVerify.cs
  src/Verify/Callbacks/VerifySettings.cs
  src/Verify/Naming/PrefixUnique.cs
Labels: Feature

#610 add TimeOnly scrubbing
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Directory.Build.props
  src/Verify.Tests/Serialization/SerializationTests.TimeOnly.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.TimeOnlyNested.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.TimeOnlyNestedWithNoScrubbing.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.TimeOnlyWithNoScrubbing.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Counter.cs
  src/Verify/Serialization/Converters/TimeConverter.cs
  src/Verify/Serialization/Scrubbers/SharedScrubber_Dates.cs
  src/Verify/Serialization/VerifierSettings_SerializationMaps.cs
Labels: Feature

#613 add DontSortDictionaries
  docs/mdsource/serializer-settings.source.md
  docs/named-tuples.md
  docs/scrubbers.md
  docs/serializer-settings.md
  readme.md
  src/Verify.Tests/Serialization/SerializationTests.DontSortDictionaries.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/CustomContractResolver.cs
  src/Verify/Serialization/SerializationSettings.cs
  src/Verify/Serialization/VerifierSettings_SerializationMaps.cs
  src/Verify/Serialization/VerifySettings_SerializationMaps.cs
  src/Verify/SettingsTask_SerializationMaps.cs
Labels: Feature

#614 Respect target frameworks for received file name
  src/Directory.Build.props
  src/OmitContentFromException/OmitContentFromExceptionTests.String.verified.txt
  src/SingleTfmTests/SingleTfmTests.csproj
  src/SingleTfmTests/Tests.cs
  src/Verify.Tests/AttributeReaderTests.Simple.verified.txt
  src/Verify.Tests/AttributeReaderTests.cs
  src/Verify.sln
  src/Verify/DerivePaths/AttributeReader.cs
  src/Verify/InternalsVisibleTo.cs
  src/Verify/Naming/PrefixUnique.cs
  src/Verify/TargetAssembly.cs
  src/Verify/buildTransitive/Verify.props
Labels: Feature

#616 add explicit using for VerifyExpecto.Verifier
  docs/naming.md
  readme.md
  src/Verify.Expecto.FSharpTests/Tests.fs
  src/Verify.Expecto.Tests/Tests.cs
  src/Verify.Expecto/buildTransitive/Verify.Expecto.props
Labels: Feature

#617 expecto Verify should return VerifyResult
  src/Verify.Expecto/Verifier.cs
  src/Verify.Expecto/Verifier_File.cs
  src/Verify.Expecto/Verifier_Json.cs
  src/Verify.Expecto/Verifier_Throws.cs
  src/Verify.Expecto/Verifier_Tuple.cs
Labels: Feature

#618 Change derive path info type and method to be strings
  docs/build-server.md
  docs/naming.md
  src/Verify.DerivePaths.Tests/Tests.cs
  src/Verify.Expecto/Verifier.cs
  src/Verify.MSTest/VerifyBase.cs
  src/Verify.NUnit/Verifier.cs
  src/Verify.Tests/Snippets/Snippets.cs
  src/Verify.Xunit/Verifier.cs
  src/Verify/DerivePaths/DerivePathInfo.cs
  src/Verify/DerivePaths/VerifierSettings.cs
  src/Verify/Extensions.cs
  src/Verify/Naming/FileNameBuilder.cs
  src/Verify/Naming/ReflectionFileNameBuilder.cs
  src/Verify/Verifier/InnerVerifier.cs
Labels: Feature

#621 Add UseTypeName, UseMethodName, and DerivePathInfo support for Expecto
  docs/naming.md
  readme.md
  readme.source.md
  src/Verify.Expecto.FSharpTests/CustomTypeName.typeNameTests.verified.txt
  src/Verify.Expecto.FSharpTests/Tests.CustomMethodName.verified.txt
  src/Verify.Expecto.FSharpTests/Tests.UseTypeName.DotNet.verified.txt
  src/Verify.Expecto.FSharpTests/Tests.fs
  src/Verify.Expecto.FSharpTests/Tests.methodNameTests.verified.txt
  src/Verify.Expecto.FSharpTests/Tests.typeNameTests.verified.txt
  src/Verify.Expecto.FSharpTests/Tests.unique.DotNet.verified.txt
  src/Verify.Expecto/Verifier.cs
Labels: Feature
