Repository VerifyTests/Verify, pull requests merged in 2022-11, with the labels that each got.

#693 Respect json settings in ToObject
  docs/serializer-settings.md
  readme.md
  src/StrictJsonTests/SerializationTests.VerifyJsonEmpty.verified.json
  src/StrictJsonTests/SerializationTests.VerifyJsonOnlyIgnoredMember.verified.json
  src/StrictJsonTests/SerializationTests.VerifyJsonRefRespectSerializerSettings.verified.json
  src/StrictJsonTests/SerializationTests.VerifyJsonTypeRespectSerializerSettings.verified.json
  src/Verify.Tests/Serialization/SerializationTests.VerifyJsonEmpty.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.VerifyJsonOnlyIgnoredMember.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.VerifyJsonRefRespectSerializerSettings.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.VerifyJsonTypeRespectSerializerSettings.verified.txt
  src/Verify.Tests/Serialization/SerializationTests.cs
  src/Verify/Serialization/Converters/JArrayConverter.cs
  src/Verify/Serialization/Converters/JObjectConverter.cs
Labels: Bug

#694 Fix Async stream/bytes usage
  docs/binary.md
  docs/verify-file.md
  docs/verify-xml.md
  src/Directory.Build.props
  src/Verify.Expecto/Verifier_Stream.cs
  src/Verify.MSTest/VerifyBase_Stream.cs
  src/Verify.NUnit/Verifier_Stream.cs
  src/Verify.NUnit/VerifyBase_Stream.cs
  src/Verify.Tests/SimpleTypeTests.Run_arg=System.Byte[].verified.bin
  src/Verify.Tests/SimpleTypeTests.Run_arg=System.Byte[].verified.txt
  src/Verify.Tests/StreamTests.ByteArrayTask.verified.bin
  src/Verify.Tests/StreamTests.FileStreamTask.verified.txt
  src/Verify.Tests/StreamTests.StreamTask.verified.bin
  src/Verify.Tests/StreamTests.cs
  src/Verify.Xunit/Verifier_Stream.cs
  src/Verify.Xunit/VerifyBase_Stream.cs
  src/Verify/Verifier/InnerVerifier_Object.cs
  src/Verify/Verifier/InnerVerifier_Stream.cs
Labels: Bug

#702 Make sure that Hidden files are included in the EnumeratedFiles
  src/Verify/Verifier/InnerVerifier_Directory.cs
Labels: Bug

#703 add SortJsonObjects
  docs/mdsource/serializer-settings.source.md
  docs/serializer-settings.md
  src/SortedJsonTest/SortedJsonTest.csproj
  src/SortedJsonTest/SortedJsonTests.Alphabetically.verified.txt
  src/SortedJsonTest/SortedJsonTests.cs
  src/Verify.sln
  src/Verify/Serialization/Converters/JObjectConverter.cs
  src/Verify/Serialization/VerifierSettings.cs
Labels: Feature

#705 update Verify.Expecto to FSharp.Core 7
  src/FSharpTests/FSharpTests.fsproj
  src/Verify.Expecto.FSharpTests/Verify.Expecto.FSharpTests.fsproj
  src/Verify.Expecto.Tests/Verify.Expecto.Tests.csproj
  src/Verify.Expecto/Verify.Expecto.csproj
Labels: Feature

#707 update to TextCopy 6.2
  src/Verify.ClipboardAccept/Verify.ClipboardAccept.csproj
Labels: Feature

#708 drop net461. add net462
  src/NullComparer/NullComparer.csproj
  src/Verify.Expecto/Verifier_Tuple.cs
  src/Verify.Expecto/Verify.Expecto.csproj
  src/Verify.MSTest/Verify.MSTest.csproj
  src/Verify.MSTest/VerifyBase_Tuple.cs
  src/Verify.NUnit/Verifier_Tuple.cs
  src/Verify.NUnit/Verify.NUnit.csproj
  src/Verify.NUnit/VerifyBase_Tuple.cs
  src/Verify.Xunit/Verifier_Tuple.cs
  src/Verify.Xunit/Verify.Xunit.csproj
  src/Verify.Xunit/VerifyBase_Tuple.cs
  src/Verify/Extensions.cs
  src/Verify/IoHelpers.cs
  src/Verify/Naming/Namer.cs
  src/Verify/Serialization/TupleConverter.cs
  src/Verify/Verifier/InnerVerifier_Tuple.cs
  src/Verify/Verify.csproj
Labels: Feature, Breaking change

#719 add VerifyJson task overloads
  src/Verify.Expecto/Verifier_Json.cs
  src/Verify.MSTest/VerifyBase_Json.cs
  src/Verify.NUnit/Verifier_Json.cs
  src/Verify.NUnit/VerifyBase_Json.cs
  src/Verify.Xunit/Verifier_Json.cs
  src/Verify.Xunit/VerifyBase_Json.cs
  src/Verify/Verifier/InnerVerifier_Json.cs
Labels: Feature

#720 add xml overloads
  src/Verify.Expecto/Verifier_Xml.cs
  src/Verify.MSTest/VerifyBase_Xml.cs
  src/Verify.NUnit/Verifier_Xml.cs
  src/Verify.NUnit/VerifyBase_Xml.cs
  src/Verify.Xunit/Verifier_Xml.cs
  src/Verify.Xunit/VerifyBase_Xml.cs
  src/Verify/Verifier/InnerVerifier_Xml.cs
Labels: Feature

#722 fix info not being passed
  docs/verify-file.md
  docs/verify-xml.md
  src/Verify.NUnit/VerifyBase_Directory.cs
  src/Verify.Tests/StreamTests.StreamsWithInfo#00.verified.bin
  src/Verify.Tests/StreamTests.StreamsWithInfo#01.verified.bin
  src/Verify.Tests/StreamTests.StreamsWithInfo.verified.txt
  src/Verify.Tests/StreamTests.cs
  src/Verify.Xunit/VerifyBase_Directory.cs
  src/Verify/Verifier/InnerVerifier_Stream.cs
Labels: Bug

#721 add more byte task overloads
  src/Verify.Expecto/Verifier_Stream.cs
  src/Verify.MSTest/VerifyBase_Stream.cs
  src/Verify.NUnit/Verifier_Stream.cs
  src/Verify.NUnit/VerifyBase_Stream.cs
  src/Verify.Xunit/Verifier_Stream.cs
  src/Verify.Xunit/VerifyBase_Stream.cs
  src/Verify/Verifier/InnerVerifier_Stream.cs
Labels: Feature

#726 Do not create artifical name for extension-only filenames
  src/ToVerify/.TextDocStartingWithDot
  src/Verify.MSTest.Tests/Tests.WithDirectory/.verified.TextDocStartingWithDot
  src/Verify.MSTest.Tests/Tests.WithDirectory/nested.with.dot/.verified.TextDocStartingWithDot
  src/Verify.NUnit.Tests/Tests.WithDirectory/.verified.TextDocStartingWithDot
  src/Verify.NUnit.Tests/Tests.WithDirectory/nested.with.dot/.verified.TextDocStartingWithDot
  src/Verify.Tests/VerifyDirectoryTests.WithDirectory/.verified.TextDocStartingWithDot
  src/Verify.Tests/VerifyDirectoryTests.WithDirectory/nested.with.dot/.verified.TextDocStartingWithDot
  src/Verify.Tests/VerifyDirectoryTests.WithDirectoryWithInfo/.verified.TextDocStartingWithDot
  src/Verify.Tests/VerifyDirectoryTests.WithDirectoryWithInfo/nested.with.dot/.verified.TextDocStartingWithDot
  src/Verify.Xunit.Tests/Tests.VerifyDirectoryWithFileScrubber/.verified.TextDocStartingWithDot
  src/Verify.Xunit.Tests/Tests.VerifyDirectoryWithFileScrubber/nested.with.dot/.verified.TextDocStartingWithDot
  src/Verify.Xunit.Tests/Tests.VerifyDirectoryWithInfo/.verified.TextDocStartingWithDot
  src/Verify.Xunit.Tests/Tests.VerifyDirectoryWithInfo/nested.with.dot/.verified.TextDocStartingWithDot
  src/Verify.Xunit.Tests/Tests.WithDirectory/.verified.TextDocStartingWithDot
  src/Verify.Xunit.Tests/Tests.WithDirectory/nested.with.dot/.verified.TextDocStartingWithDot
  src/Verify/Extensions.cs
  src/Verify/IoHelpers.cs
  src/Verify/Verifier/InnerVerifier.cs
  src/Verify/Verifier/InnerVerifier_Directory.cs
Labels: Feature

#728 make InnerVerifier public
  src/Directory.Build.props
  src/Verify/Verifier/InnerVerifier.cs
  src/Verify/Verifier/InnerVerifier_Directory.cs
  src/Verify/Verifier/InnerVerifier_File.cs
  src/Verify/Verifier/InnerVerifier_Inner.cs
  src/Verify/Verifier/InnerVerifier_Json.cs
  src/Verify/Verifier/InnerVerifier_Object.cs
  src/Verify/Verifier/InnerVerifier_Stream.cs
  src/Verify/Verifier/InnerVerifier_String.cs
  src/Verify/Verifier/InnerVerifier_Task.cs
  src/Verify/Verifier/InnerVerifier_Throws.cs
  src/Verify/Verifier/InnerVerifier_Tuple.cs
  src/Verify/Verifier/InnerVerifier_Xml.cs
Labels: Feature
