Repository VerifyTests/Verify, pull requests merged in 2023-07, with the labels that each got.

#934 update to DiffEngine v 12
  src/Directory.Build.props
  src/Verify.ClipboardAccept/Verify.ClipboardAccept.csproj
  src/Verify/Verify.csproj
Labels: Improvement

#938 Bugfix for VerifyXml
  src/Verify.Tests/XmlTests.EmptyTag.verified.xml
  src/Verify.Tests/XmlTests.EmptyTagWithAttributes.verified.xml
  src/Verify.Tests/XmlTests.IgnoreAttribute.verified.xml
  src/Verify.Tests/XmlTests.ScrubAttribute.verified.xml
  src/Verify.Tests/XmlTests.cs
  src/Verify/Verifier/InnerVerifier_Xml.cs
Labels: Bug

#945 expose GetNameForParameter
  src/Directory.Build.props
  src/Verify/Naming/VerifierSettings.cs
Labels: Feature
