Repository VerifyTests/Verify, pull requests merged in 2023-09, with the labels that each got.

#991 Update to argon 0.9.0
  docs/serializer-settings.md
  src/FSharpTests/FSharpTests.fsproj
  src/Verify/Serialization/Converters/StringBuilderConverter.cs
  src/Verify/Serialization/Converters/StringWriterConverter.cs
  src/Verify/Serialization/SerializationSettings.cs
  src/Verify/Verify.csproj
Labels: Feature

#992 dont pollute global converters
  docs/serializer-settings.md
  src/Directory.Build.props
  src/Verify/Serialization/SerializationSettings.cs
Labels: Bug

#993 Explicitly reject unbounded streams
  docs/verify-file.md
  docs/verify-xml.md
  src/Shared.sln.DotSettings
  src/Verify.Tests/StreamTests.UnboundedStream.verified.txt
  src/Verify.Tests/StreamTests.cs
  src/Verify.Tests/UnboundedStream.cs
  src/Verify/Verifier/InnerVerifier_Stream.cs
  src/Verify/Verifier/VerifyException.cs
Labels: Feature

#1001 Fix bug with non scoped stream for received file
  src/Directory.Build.props
  src/Verify.Tests/StreamTests.cs
  src/Verify/IoHelpers.cs
Labels: Bug

#1005 DiffEngine 12.3
  src/Directory.Build.props
  src/Verify.ClipboardAccept/Verify.ClipboardAccept.csproj
  src/Verify/Verify.csproj
Labels: Feature

#1007 dont escape Property name
  src/Verify/Serialization/VerifyJsonWriter.cs
Labels: Improvement

#1008 update to Argon 0.11
  src/FSharpTests/FSharpTests.fsproj
  src/Verify/Verify.csproj
Labels: Improvement
